default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tanya
  password: 25051960
  host:     localhost

development:
  <<: *default
  database: my-app_development

test:
  <<: *default
  database: my-app_test

production:
  <<: *default
  database: my-app_production  



